# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', django_google_maps.fields.AddressField(max_length=100)),
                ('location', django_google_maps.fields.GeoLocationField(blank=True, max_length=100)),
            ],
        ),
    ]
