# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0002_hood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hood',
            old_name='location',
            new_name='geolocation',
        ),
    ]
